### ISSUE TITLE
Mod disables chance-based blue portal spawn

### ISSUE THREAD

**Issue by MeatMorning** [nuxlar/Looper#1]
Even though blue orb is announced, blue portal isn't created

**Comment by nuxlar** [comment]
it should disable it if you have a blue portal set for that stage so 2 don't spawn. Was the stage on vanilla config (default: 0) or it had a portal spawn (any)? If so what was the portal spawn number? Thanks for letting me know!

**Comment by MeatMorning** [comment]
it was 0. Similar mechanic in "ConfigurableBazaar" also disabled all blue portal spawns if any stage was set to guaranty shop spawn.

**Comment by nuxlar** [comment]
fixed in the latest update!
