### ISSUE TITLE
Suggestion: Multiple portals types/random selection of portals?

### ISSUE THREAD

**Issue by Darkmega18** [nuxlar/Looper#2]
Config option for having multiple choices of portals that can appear, for run variance/choice.

also:

a possible mode where the portal/portals that appear is randomized from a selection of possible portals.

For example, I can set twisted scav to have a gold and bazaar portal appear at once.
But in random mode, I can set X number of portals (1 or 2) in a setting thats only active if random mode is on and then it'll pick from bazaar, locus, gold or null if I set those options. But not deep void or celestial.

Same with mithrix, have config options to set each portal separately to true or false for portals that can/will appear, then a 0/1 option for random (picks X portals from the enabled) or exact mode (throws all the enabled portals down in the surrounding area).

**Comment by nuxlar** [comment]
not adding any new features to any of my mods currently, only bug fixes if the bug is bad enough.

**Comment by Darkmega18** [comment]
D: is everyone leaving modding suddenly? you're the second person who's feature frozen when I've come to make suggestions/reports. :<
